server:
  port: 9000

#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atcrowdfunding
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat  #开启监控过滤器  这是druid的监控器
  redis:
    database: 1
    host: 192.168.188.146
    port: 6379
  application:
    name: SCW-ORDER

#my-batis
mybatis:
  mapper-locations: classpath:com/offcn/order/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka